name: cd

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.122.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
              --minify \

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCS_SA_CREDENTIALS }}"

      - name: Setup Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Upload to GCS bucket
        run: gsutil -m rsync -d -r ${{ github.workspace }}/public gs://${{ secrets.GCS_BUCKET_NAME }}
